baseURL = 'https://lukegreen.xyz'
languageCode = 'en-us'
title = 'Luke Green'
theme = 'paperesque'
enableRobotsTXT = true

[[params.topmenu]]
name = 'about'
url = 'about/'

[[params.topmenu]]
name = 'thoughts'
url = 'thoughts/'

[[params.topmenu]]
name = 'alternatives'
url = 'alternatives/'

[[params.topmenu]]
name = 'scratch'
url = 'scratch/'
